//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btn_Details {
            get {
                return ResourceManager.GetString("btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        public static string display_401 {
            get {
                return ResourceManager.GetString("display_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string display_401_Description {
            get {
                return ResourceManager.GetString("display_401_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        public static string display_403 {
            get {
                return ResourceManager.GetString("display_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not access.
        /// </summary>
        public static string display_403_Description {
            get {
                return ResourceManager.GetString("display_403_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        public static string display_404 {
            get {
                return ResourceManager.GetString("display_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string display_404_Description {
            get {
                return ResourceManager.GetString("display_404_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string display_500 {
            get {
                return ResourceManager.GetString("display_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string display_500_Description {
            get {
                return ResourceManager.GetString("display_500_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string display_Actions {
            get {
                return ResourceManager.GetString("display_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit.
        /// </summary>
        public static string display_AddEdit {
            get {
                return ResourceManager.GetString("display_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totara App.
        /// </summary>
        public static string display_AppName {
            get {
                return ResourceManager.GetString("display_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find ....
        /// </summary>
        public static string display_Buscar {
            get {
                return ResourceManager.GetString("display_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ?.
        /// </summary>
        public static string display_ConfirmOnDelete {
            get {
                return ResourceManager.GetString("display_ConfirmOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of {0}.
        /// </summary>
        public static string display_DetailsOf {
            get {
                return ResourceManager.GetString("display_DetailsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of {0}.
        /// </summary>
        public static string display_ListOfXXX {
            get {
                return ResourceManager.GetString("display_ListOfXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string display_Welcome {
            get {
                return ResourceManager.GetString("display_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gateway Application.
        /// </summary>
        public static string display_WelcomeMessage {
            get {
                return ResourceManager.GetString("display_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors, for more information check validation errors.
        /// </summary>
        public static string Exception_ApplicationValidationError {
            get {
                return ResourceManager.GetString("Exception_ApplicationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must been provided just one mode and only one mode. Either ShowMode, EditMode or DeleteMode..
        /// </summary>
        public static string Exception_MultipleModeOnShowView {
            get {
                return ResourceManager.GetString("Exception_MultipleModeOnShowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property specified {0} can not be defined for ordering collection of {1}..
        /// </summary>
        public static string Exception_NullFieldOnOrderingEntity {
            get {
                return ResourceManager.GetString("Exception_NullFieldOnOrderingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist.
        /// </summary>
        public static string message_ItemDoesNotExist {
            get {
                return ResourceManager.GetString("message_ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string message_PageNotFound {
            get {
                return ResourceManager.GetString("message_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        public static string message_SuccesfullyAdded {
            get {
                return ResourceManager.GetString("message_SuccesfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string message_SuccesfullyDeleted {
            get {
                return ResourceManager.GetString("message_SuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited.
        /// </summary>
        public static string message_SuccesfullyEdited {
            get {
                return ResourceManager.GetString("message_SuccesfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        public static string page_401 {
            get {
                return ResourceManager.GetString("page_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        public static string page_403 {
            get {
                return ResourceManager.GetString("page_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        public static string page_404 {
            get {
                return ResourceManager.GetString("page_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string page_500 {
            get {
                return ResourceManager.GetString("page_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string page_Index {
            get {
                return ResourceManager.GetString("page_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UsuarioDto {
            get {
                return ResourceManager.GetString("UsuarioDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UsuarioDtoEmail {
            get {
                return ResourceManager.GetString("UsuarioDtoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UsuarioDtoNombre {
            get {
                return ResourceManager.GetString("UsuarioDtoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsuarioDtos {
            get {
                return ResourceManager.GetString("UsuarioDtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string UsuarioDtoSuspended {
            get {
                return ResourceManager.GetString("UsuarioDtoSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsuarioDtoUsername {
            get {
                return ResourceManager.GetString("UsuarioDtoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is incorrect.
        /// </summary>
        public static string validation_BadEmailAddress {
            get {
                return ResourceManager.GetString("validation_BadEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required.
        /// </summary>
        public static string validation_FieldRequired {
            get {
                return ResourceManager.GetString("validation_FieldRequired", resourceCulture);
            }
        }
    }
}
