//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string btn_Details {
            get {
                return ResourceManager.GetString("btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string display_Actions {
            get {
                return ResourceManager.GetString("display_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar / Editar.
        /// </summary>
        public static string display_AddEdit {
            get {
                return ResourceManager.GetString("display_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar ....
        /// </summary>
        public static string display_Buscar {
            get {
                return ResourceManager.GetString("display_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea eliminar ?.
        /// </summary>
        public static string display_ConfirmOnDelete {
            get {
                return ResourceManager.GetString("display_ConfirmOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de  {0}.
        /// </summary>
        public static string display_DetailsOf {
            get {
                return ResourceManager.GetString("display_DetailsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de validación, compruebe los errores de la validación para más información..
        /// </summary>
        public static string Exception_ApplicationValidationError {
            get {
                return ResourceManager.GetString("Exception_ApplicationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar solo un modo al mostrar la vista. Ó ShowMode ó EditMode ó DeleteMode..
        /// </summary>
        public static string Exception_MultipleModeOnShowView {
            get {
                return ResourceManager.GetString("Exception_MultipleModeOnShowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad especificada {0} no puede ser seleccionada para ordernar colección de {1}..
        /// </summary>
        public static string Exception_NullFieldOnOrderingEntity {
            get {
                return ResourceManager.GetString("Exception_NullFieldOnOrderingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela.
        /// </summary>
        public static string GatewayDtoCommon {
            get {
                return ResourceManager.GetString("GatewayDtoCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ipv4.
        /// </summary>
        public static string GatewayDtoCommonIpv4Address {
            get {
                return ResourceManager.GetString("GatewayDtoCommonIpv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string GatewayDtoCommonName {
            get {
                return ResourceManager.GetString("GatewayDtoCommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periféricos.
        /// </summary>
        public static string GatewayDtoCommonPeripherals {
            get {
                return ResourceManager.GetString("GatewayDtoCommonPeripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarelas.
        /// </summary>
        public static string GatewayDtoCommons {
            get {
                return ResourceManager.GetString("GatewayDtoCommons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad no existe.
        /// </summary>
        public static string message_ItemDoesNotExist {
            get {
                return ResourceManager.GetString("message_ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sido adicionado/a satisfactoriamente.
        /// </summary>
        public static string message_SuccesfullyAdded {
            get {
                return ResourceManager.GetString("message_SuccesfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sido eliminado/a satisfactoriamente.
        /// </summary>
        public static string message_SuccesfullyDeleted {
            get {
                return ResourceManager.GetString("message_SuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sido editado/a satisfactoriamente.
        /// </summary>
        public static string message_SuccesfullyEdited {
            get {
                return ResourceManager.GetString("message_SuccesfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periférico.
        /// </summary>
        public static string PeripheralDtoCommon {
            get {
                return ResourceManager.GetString("PeripheralDtoCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha creado.
        /// </summary>
        public static string PeripheralDtoCommonCreatedDate {
            get {
                return ResourceManager.GetString("PeripheralDtoCommonCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela.
        /// </summary>
        public static string PeripheralDtoCommonGatewayId {
            get {
                return ResourceManager.GetString("PeripheralDtoCommonGatewayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periféricos.
        /// </summary>
        public static string PeripheralDtoCommons {
            get {
                return ResourceManager.GetString("PeripheralDtoCommons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string PeripheralDtoCommonStatus {
            get {
                return ResourceManager.GetString("PeripheralDtoCommonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string PeripheralDtoCommonVendor {
            get {
                return ResourceManager.GetString("PeripheralDtoCommonVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string validation_FieldRequired {
            get {
                return ResourceManager.GetString("validation_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección Ip no es válida.
        /// </summary>
        public static string validation_Ipv4AddressBadFormat {
            get {
                return ResourceManager.GetString("validation_Ipv4AddressBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No son permitidos más de {0} periféricos por pasarela.
        /// </summary>
        public static string validation_MaxPeriphelsAllowed {
            get {
                return ResourceManager.GetString("validation_MaxPeriphelsAllowed", resourceCulture);
            }
        }
    }
}
