// <auto-generated />
using Infrastructure.Domain.UnitOfWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UnitOfWorkContainer))]
    [Migration("20220720215337_AddRutToUser")]
    partial class AddRutToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rut")
                        .HasColumnType("longtext");

                    b.Property<bool>("Suspended")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Email = "vvillagran@dl.cl",
                            Nombre = "VALESKA VILLAGR",
                            Rut = "16782703-9",
                            Suspended = false,
                            Username = "16782703-9"
                        },
                        new
                        {
                            Id = 15,
                            Email = "17768779-0@pilotoapp.com",
                            Nombre = "Lilian Carolina Gonzalez Silva",
                            Rut = "",
                            Suspended = false,
                            Username = "17768779-0"
                        },
                        new
                        {
                            Id = 19,
                            Email = "25338108-6@pilotoapp.com",
                            Nombre = "Alejandro Sarmiento Millares",
                            Rut = "",
                            Suspended = false,
                            Username = "25338108-6"
                        },
                        new
                        {
                            Id = 20,
                            Email = "26402139-1@pilotoapp.com",
                            Nombre = "ANA GABRIELA DUR",
                            Rut = "26402139-1",
                            Suspended = false,
                            Username = "26402139-1"
                        },
                        new
                        {
                            Id = 81,
                            Email = "17050718-5@pilotoapp.com",
                            Nombre = "Pamela de los Angeles Lira Morales",
                            Rut = "17050718-5",
                            Suspended = false,
                            Username = "17050718-5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
